### ISSUE TITLE
after setting up, when Running run.py, got ValueError!

### ISSUE THREAD

**Issue by 786449611** [vn-crypto/vnpy_mt5#8]
(Win11, using mt5 XMtrading account (only have hedge account), successfully followed the guide.)
after installing  TA-lib, I am trying to run the Run.py script, but got following error.
---
Installing collected packages: numpy, TA-Lib
Successfully installed TA-Lib-0.4.26 numpy-2.0.0

PS C:\Users\xxxx> & D:/anaconda3/envs/vectorbtpro/python.exe d:/Downloads/vnpy_mt5-main/vnpy_mt5-main/script/run.py
Traceback (most recent call last):
  File "d:\Downloads\vnpy_mt5-main\vnpy_mt5-main\script\run.py", line 2, in <module>
    from vnpy_evo.trader.engine import MainEngine
  File "D:\anaconda3\envs\vectorbtpro\lib\site-packages\vnpy_evo\trader\engine.py", line 1, in <module>
    from vnpy.trader.engine import *
  File "D:\anaconda3\envs\vectorbtpro\lib\site-packages\vnpy\trader\engine.py", line 43, in <module>
    from .setting import SETTINGS
  File "D:\anaconda3\envs\vectorbtpro\lib\site-packages\vnpy\trader\setting.py", line 9, in <module>
    from .utility import load_json
  File "D:\anaconda3\envs\vectorbtpro\lib\site-packages\vnpy\trader\utility.py", line 15, in <module>
    import talib
  File "D:\anaconda3\envs\vectorbtpro\lib\site-packages\talib\__init__.py", line 93, in <module>
    from ._ta_lib import (
  File "talib/_ta_lib.pyx", line 1, in init talib._ta_lib

**ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject**

**Comment by 786449611** [comment]
@vnpy @veighna-global @vn-crypto 
Could you take a look? 
and Where to implement a self-defined python strategy to make it work alive? Could you give an example?
thanks!
